ERROR: user 'test2' does not exists
